### ISSUE TITLE
Where is the source code of the agenda generating script?

### ISSUE THREAD

**Issue by hober** [w3ctag/process#12]
I figured it would have its own repo or that it would be in a subdirectory of the `meetings` repo, but neither appears to be the case.

**Comment by plinss** [comment]
It’s currently a glitch app. When I changed it to scan all repos for milestones it started running in to API rate limits very quickly.

I’m going to rewrite it as a Python app that’ll run on w3ctag.org, so it can run authenticated and have a higher rate limit, along with a few bots. I‘ll make repos for them when I do that.
