### ISSUE TITLE
Document design review lifecycle

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/process#22]
As discussed in today's breakout C, it would be good to write down how the design review process works, as it's currently quite opaque.
This would benefit both new TAG members, as well as people outside the TAG looking in.

Things like:

* What does it mean that someone is assigned to an issue?
* What do the various labels mean and when are they added? Which labels mean that something has "passed TAG review"?
* When is an issue discussed? The fact that issues come up multiple times in multiple calls was not clear to me when I first joined. 
* When is an issue closed? Things like, we don't close issues in breakouts, and what the exceptions are. What are the criteria for closing an issue?

**Comment by torgo** [comment]
@LeaVerou can you review the above PR an see if it addresses these issues? @ylafon do you think we need to say something additional about WICG?

**Comment by torgo** [comment]
Closed with https://github.com/w3ctag/tag.w3.org/pull/36/
