### ISSUE TITLE
www-tag@w3.org list vs Github - suggest updating mailing list blurb

### ISSUE THREAD

**Issue by danbri** [w3ctag/process#25]
https://tag.w3.org/workmode/ says

> 4. The www-tag Mailing List
Issues that aren’t related to a specification can be discussed on the www-tag mailing list. Note that this is also used as a general discussion list for Web architecture, and so if you need a response from the TAG, it’s best to get something into the design-reviews issue tracker.

http://lists.w3.org/Archives/Public/www-tag/ says 

> This is the archive of the public discussion list of the W3C Technical Architecture Group. Please limit your use of this list to discussions issues of Web architecture. Comments in this archive are visible to the public.

The former is relatively clear that the TAG don't commit to listen to the list. It perhaps understates the extent to which the TAG are more Github-focussed. But the mailing list description doesn't seem to have changed since the list was originally set up, back when we had terrible rambling centi-threads about the referential semantics of URIs.

Suggestion updating http://lists.w3.org/Archives/Public/www-tag/ to something like:

> This is the archive of the public discussion list for issues around Web architecture, and was formally used for the work of the W3C Technical Architecture Group. TAG-related topics remain welcome, but to engage with the TAG more explicitly please see https://tag.w3.org/workmode/  (and e.g. use the design-reviews Github workflow). From the recent threads on that list (including [from](https://lists.w3.org/Archives/Public/www-tag/2021Jan/0000.html) @timbl) it seems that folks on the list might have missed a memo.

/cc @ylafon as it seems staff-contact kind of a topic; @hadleybeeman as we discussed this earlier.

**Comment by torgo** [comment]
Hi @danbri the text may need to be updated but I'm not sure that's the right slant. We do welcome discussion on the www-tag list and if someone posts to the www-tag list appropriately then we will bring it to our agenda (as we did just this past week). However we're not using the list as discussion forum for TAG work, especially design reviews and updates to TAG documents. That work is happening in GitHub.
